### ISSUE TITLE
Very slow processing of downloaded cc judgments

### ISSUE THREAD

**Issue by lukdumi** [CeON/saos#691]
13000 judgments/6h
... and it slows down:
see batch execution no 196

**Comment by madryk** [comment]
Slow processing was caused by removing references to judgments in enrichment tags.
We reached to conclusion that our concept of removing references in overwriting judgments is wrong.
Let's assume that we have enrichment tag with references (B -> A, C).
Now we assume that job reached overwriting of judgment A (judgment A possibly have some changes).
What we did is modify enrichment tag to (B -> C), but what we know is judgment B has not changed at all (it will change only if overwriting will happen for it too). If it has not changed than reference to A is correct.

Only situation where we need to worry about reference removing is when judgment A will be deleted.
Then enrichment tag (B -> A, C) will point to judgment with id that is not present in database.
That will be corrected in a seperate ticket.
